# coding: utf-8

# flake8: noqa
"""
    Ipefr servers Balancer

    Simple IP balanser  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vinogradov.alek@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.results import Results
