# coding: utf-8

"""
    Ipefr servers Balancer

    Simple IP balanser  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: vinogradov.alek@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.server_api import ServerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestServerApi(unittest.TestCase):
    """ServerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.server_api.ServerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_ip(self):
        """Test case for delete_ip

        delete server IP  # noqa: E501
        """
        pass

    def test_get_ip(self):
        """Test case for get_ip

        optain server IP  # noqa: E501
        """
        pass

    def test_post_ip(self):
        """Test case for post_ip

        send server ip to balancer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
