name: Django tests

on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@main
     - name: Install Python 3.8
       uses: actions/setup-python@v4
       with:
         python-version: '3.8'

     - name: Install dependencies
       uses: VaultVulp/action-pipenv@v2.0.1
       with:
         command: install -d

     - name: Run Django tests
       uses: VaultVulp/action-pipenv@v2.0.1
       with:
         command: run test
