name: Django tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: SECRET_KEY
      DEBUG: False
      SUPPORT_EMAIL: noreply@5gst.ru
    steps:
    - uses: actions/checkout@main
    - name: Install pip, pipenv and packages from Pipfile
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Run tests
      run: |
        pipenv run test
